# This is a test project for Docker Compose that allows maintainers of
# docker-dev, who also run docker-dev, to just go to
# https://docker-dev.test and make sure everything is working, without
# involving the dependency tree of any one application they might be
# running on their machine.
version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "${PORT:-3000}:80"
