name: Build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - linux
          - darwin
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.11.x
      - run: make
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: amd64
      - uses: actions/upload-artifact@v1
        with:
          name: docker-dev-${{ matrix.os }}-amd64
          path: ./docker-dev
