name: Release
on:
  push:
    tags: [v*]
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: src/github.com/tubbo/docker-dev
      - uses: actions/setup-go@v1
        with:
          go-version: 1.11.x
      - run: make release
        env:
          RELEASE: ${{ github.ref }}
          GOPATH: /home/runner/work/docker-dev
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docker-dev-${{ github.ref }}-darwin-amd64.zip
          asset_name: docker-dev-${{ github.ref }}-macos-amd64.zip
          asset_content_type: application/zip
      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docker-dev-${{ github.ref }}-linux-amd64.tar.gz
          asset_name: docker-dev-${{ github.ref }}-linux-amd64.tar.gz
          asset_content_type: application/gzip
